# Generated by Django 5.0.3 on 2024-04-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_app', '0001_initial'),
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.credit_card')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.cost')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.date_time')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.parking_lot')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_veh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.vehicle')),
            ],
        ),
    ]
