# Generated by Django 5.0.3 on 2024-04-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aut_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.user')),
            ],
        ),
    ]
