# Generated by Django 5.0.3 on 2024-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_name', models.CharField(max_length=15)),
                ('bank_add1', models.CharField(max_length=20)),
                ('bank_add2', models.CharField(max_length=20)),
                ('bank_city', models.CharField(max_length=15)),
                ('bank_state', models.CharField(max_length=2)),
                ('bank_zip', models.CharField(max_length=5)),
                ('bank_acctnum', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_routnum', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Credit_Card',
            fields=[
                ('card_fname', models.CharField(max_length=15)),
                ('card_lname', models.CharField(max_length=20)),
                ('card_add1', models.CharField(max_length=20)),
                ('card_add2', models.CharField(max_length=20)),
                ('card_city', models.CharField(max_length=20)),
                ('card_state', models.CharField(max_length=20)),
                ('card_zip', models.CharField(max_length=2)),
                ('card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('card_SecNum', models.IntegerField()),
                ('card_ExpDate', models.DateField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Date_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=15)),
                ('user_lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('user_add1', models.CharField(max_length=20)),
                ('user_add2', models.CharField(max_length=20)),
                ('user_city', models.CharField(max_length=20)),
                ('user_state', models.CharField(max_length=20)),
                ('user_zip', models.CharField(max_length=2)),
                ('user_email', models.EmailField(default='sombody@email.com', max_length=254)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('veh_year', models.IntegerField()),
                ('veh_make', models.CharField(max_length=12)),
                ('veh_model', models.CharField(max_length=15)),
                ('veh_color', models.CharField(max_length=10)),
                ('veh_licnum', models.CharField(max_length=7)),
                ('veh_vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
            ],
        ),
    ]
