# Generated by Django 5.0.3 on 2024-05-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration_app", "0002_alter_user_user_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.EmailField(default="@email.com", max_length=254),
        ),
    ]
