# Generated by Django 5.0.3 on 2024-04-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_app', '0001_initial'),
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.credit_card')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.cost')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.date_time')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.parking_lot')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.vehicle')),
            ],
        ),
    ]
