# Generated by Django 5.0.3 on 2024-04-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('cost_confirm', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cost_SpPrice', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=15)),
                ('lot_add1', models.CharField(max_length=15)),
                ('lot_spcstat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.date_time')),
            ],
        ),
        migrations.CreateModel(
            name='Book_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.user')),
            ],
        ),
    ]
