# Generated by Django 5.0.3 on 2024-05-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking_lot",
            name="lot_avaspace",
            field=models.IntegerField(default=True),
        ),
    ]
