# Generated by Django 5.0.3 on 2024-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0002_parking_lot_lot_avaspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking_lot",
            name="lot_totspace",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="parking_lot",
            name="lot_avaspace",
            field=models.IntegerField(default=100),
        ),
    ]
